### PR TITLE
Ft syncronize scroll

### PR DESCRIPTION
**Pull request by moacirrf**
Improve scroll of preview window and code editor, based on content  of visible area.

https://user-images.githubusercontent.com/950706/204622338-7448a59f-05ac-4508-b049-21213e5c4e81.mp4

### How it works ?

1-  Change the way that Html is generated to track the original position of text on md file.
Example:

image

will generate something like

    <h2 id="736-750">
      <span id="739-750">Blockquotes</span>
    </h2>
    <blockquote>
      <p id="753-825">
        <span id="753-824">Dorothy followed her through many of the beautiful 
        rooms in her castle.</span>
      </p>
    </blockquote>
   
      
"739-750" is the start and end position of text Blockquotes on md file.

2-  If the first line of viewport is in position between 736-750.

image

3-  So we scroll the preview panel to id ="736-750".

image

### CODE REVIEW

**Comment by Chris2011** [comment]
Awesome work, will test it soon :).

**Comment by moacirrf** [comment]
> Awesome work, will test it soon :).

Thanks @Chris2011

**Comment by Chris2011** [comment]
Would be good if you can create a new release. Except you want to do other integrations first.

**Comment by moacirrf** [comment]
Will do some others integrations first, i will try configure github packages to generate files directly on github packages when publish to main branch.
I think it's possible to do that don't you think?

Thank you very much for your feedbacks

**Comment by Chris2011** [comment]
Thx for the info. Sure that will be possible, just create an github action/workflow which will build and add the nbm file as an artifact or smth like that. Really appreciate your work :)

**Comment by moacirrf** [comment]
Hi @Chris2011 
Now when push on main branch will generate a snapshot version.

[https://github.com/moacirrf/netbeans-markdown/releases](
https://github.com/moacirrf/netbeans-markdown/releases)

I'll keep improving the sync to make it more and more accurate, there's a lot of room for optimization in this part.

cheers

**Pull request merged**
